version: '3'

services:
  jekyll:
    container_name: cesuarez.github.io
    image: jekyll/jekyll:4.0
    command: jekyll serve --verbose --host 0.0.0.0
    volumes:
      - .:/srv/jekyll
    ports:
      - 4000:4000
